version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.6.1
    # ports:
    #   - "5000:5000"
    #   - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    ports:
      - "8301:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - frontend
      - backend
    deploy:
      labels:
        - "traefik.backend=kibana"
        - "traefik.frontend.rule=PathPrefix:/kibana"
        - "traefik.port=5601"
        - "traefik.enable=true"
        - "traefik.docker.network=ksys_front_net"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml

networks:
  frontend:
    external: true
    name: ksys_front_net
  backend:  
    driver: overlay
    attachable: true